#!/bin/bash

# A simple script to perform the intialisation of an experiment.
README_FILE=README.md
DEFAULT_DATA_ROOT=

function out_line {
	echo $* >> $README_FILE
}

function create_readme {

	local repo=$1
	local data=$2

	if [ ! -f $README_FILE ]
	then
		out_line "---"
		out_line "AUTHOR=$(whoami)"
		out_line "DATE=$(date '+%Y-%m-%d %H:%M:%S')"
		out_line "EXPERIMENT_TAG=$(basename $repo)"
		out_line "REPO_PATH=$repo"
		out_line "DATA_ROOT=$data"
		out_line "---"
	fi

	# Add the README file to the git repo.
	git add $README_FILE
}

function create_gitignore {
	local repo=$1
	local gitignore_file=".gitignore"
	if [ ! -f $gitignore_file ]
	then
		echo "# Ignore the following files by default" >> $gitignore_file
		echo "*.caffemodel" >> $gitignore_file
		echo "*.npy" >> $gitignore_file
		echo "*.solverstate" >> $gitignore_file
		echo "*.caffetrace*" >> $gitignore_file
	fi

	# Add the .gitignore file to the git repo.
	git add $gitignore_file
}


function create_subfolders {
	local repo=$1

	mkdir -p $repo/src
}

function init_hooks {

	local repo=$1/.git/hooks
	local script=$2

	if [ ! -f $repo/pre-commit ]
	then
		ln -s $script/pre-commit-filter.sh $repo/pre-commit

	fi
	if [ ! -f $repo/post-commit ]
	then
		ln -s $script/post-commit-copy.sh $repo/post-commit
	fi

}

# Determine the path where the repo should be created.
if [ $# -lt 1 ]
then
	username=$(whoami)
	username=${username//_/}
	path_arg=$(whoami)_$(date '+%Y_%m_%d')
else
	path_arg=$1
	shift
fi

current_dir=$PWD

# Initialise a git repository at the specified path.

if [ "$path_arg" == "." ]
then
	REPO_PATH=$current_dir
else
	REPO_PATH=$current_dir/$path_arg

	if [ -d $REPO_PATH ]
	then
		echo ""
		echo "The folder for the specified experiment already exists"
		echo "    $REPO_PATH"
		echo ""
		read -p "Continue? y/[N]: " response
		if [ "${response:-N}" != "y" ]
		then
			exit 0
		fi
	fi

fi

# Initialise a GIT repo in the specified path.
echo ""
git init $REPO_PATH
echo ""

# Setup some Repo contents.
cd $REPO_PATH
repo_name=$(basename $REPO_PATH)
# Determine the DATA_ROOT
DATA_PATH=${DATA_ROOT:-${DEFAULT_DATA_ROOT}}

# Setup the readme.
create_readme $REPO_PATH $DATA_PATH
# Setup the gitignore
create_gitignore $REPO_PATH
# Create the default folders.
create_subfolders $REPO_PATH

# Create the git hooks
SCRIPT_PATH="$(dirname $(which exp_init))/git_hooks"
init_hooks $REPO_PATH $SCRIPT_PATH

if [ $EXP_INIT_DEBUG ]
then
	git status
fi

# As a final step perform an initial commit.
# TODO: This should not be done if there are already files in the folder.
git commit -m "Initial commit (Automatic)."


if [ $EXP_INIT_DEBUG ]
then
	git status
	# DEBUG: Print the added readme
	cat $REPO_PATH/$README_FILE
fi

# Return to the previous directory.
cd $current_dir
